import Link from "next/link";
import { ArrowLeft, Boxes, Building2, FileText, Layers3, ListChecks, Upload, Users } from "lucide-react";

const models = [
  ["Architektur", "ARCH", "IFC", "bereit für Upload"],
  ["Heizung", "HEI", "IFC", "bereit für Upload"],
  ["Lüftung", "LUE", "IFC", "bereit für Upload"],
  ["Sanitär", "SAN", "IFC", "bereit für Upload"],
  ["Koordination", "KOORD", "IFC", "bereit für Upload"],
];

export default function ZH31Page() {
  return <main className="min-h-screen bg-[#f5f8f9] text-slate-900">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><div><div className="flex items-center gap-3"><Boxes className="h-7 w-7 text-[#0097c3]"/><h1 className="font-serif text-3xl">BOG Fusion</h1></div><p className="mt-1 text-sm text-slate-500">ZH31 Ausstellungsstrasse · Pilotprojekt</p></div><Link href="/fusion" className="inline-flex items-center gap-2 rounded-md border border-slate-200 px-4 py-2 text-sm font-medium text-slate-700 hover:border-[#0097c3] hover:text-[#0097c3]"><ArrowLeft className="h-4 w-4"/>Meine Projekte</Link></div></header>
    <section className="mx-auto max-w-7xl px-6 py-8">
      <div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#0097c3]">ZH31</p><h2 className="mt-2 font-serif text-3xl">Ausstellungsstrasse</h2><p className="mt-2 text-sm text-slate-500">Zürich · ARCH · HEI · LUE · SAN · KOORD</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">Pilotprojekt aktiv</span></div>
      <div className="grid gap-4 md:grid-cols-4"><div className="rounded-xl border bg-white p-4"><Building2 className="h-5 w-5 text-[#0097c3]"/><div className="mt-3 text-2xl font-semibold">5</div><div className="text-xs text-slate-500">IFC Fachmodelle</div></div><div className="rounded-xl border bg-white p-4"><FileText className="h-5 w-5 text-[#0097c3]"/><div className="mt-3 text-2xl font-semibold">DWG</div><div className="text-xs text-slate-500">2D Planbestand</div></div><div className="rounded-xl border bg-white p-4"><ListChecks className="h-5 w-5 text-[#0097c3]"/><div className="mt-3 text-2xl font-semibold">0</div><div className="text-xs text-slate-500">Offene Issues</div></div><div className="rounded-xl border bg-white p-4"><Users className="h-5 w-5 text-[#0097c3]"/><div className="mt-3 text-2xl font-semibold">Pilot</div><div className="text-xs text-slate-500">Projektzugriff</div></div></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_340px]">
        <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="font-serif text-xl">Koordinationsbereich</h3><p className="mt-1 text-xs text-slate-500">Später: 2D / 3D / Split View</p></div><div className="flex rounded-md border p-1 text-xs font-semibold"><span className="rounded bg-[#0097c3] px-3 py-1.5 text-white">3D</span><span className="px-3 py-1.5">2D</span><span className="px-3 py-1.5">Split</span></div></div><div className="grid min-h-[430px] place-items-center bg-gradient-to-br from-slate-50 to-cyan-50/40 p-8 text-center"><div className="max-w-md"><Layers3 className="mx-auto h-12 w-12 text-[#0097c3]"/><h4 className="mt-4 font-serif text-2xl">ZH31 Modellraum</h4><p className="mt-3 text-sm leading-6 text-slate-500">Hier werden heute Abend die echten IFC-Fachmodelle des Projekts geladen. Danach testen wir Überlagerung, Navigation, Gewerke, Elementauswahl und anschliessend Clashes.</p><button className="mt-5 inline-flex items-center gap-2 rounded-md bg-[#0097c3] px-4 py-2.5 text-sm font-semibold text-white"><Upload className="h-4 w-4"/>IFC laden · folgt im Viewer</button></div></div></section>
        <aside className="rounded-xl border border-slate-200 bg-white"><div className="border-b px-5 py-4"><h3 className="font-semibold">Fachmodelle</h3><p className="mt-1 text-xs text-slate-500">Pilotdatensatz ZH31</p></div><div className="divide-y">{models.map(([name,code,type,status])=><div key={code} className="p-4"><div className="flex items-center justify-between"><div><div className="font-medium">{name}</div><div className="mt-1 text-xs text-slate-500">{code} · {type}</div></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-medium text-slate-600">{status}</span></div></div>)}</div><div className="border-t p-4"><div className="font-medium">2D Pläne</div><p className="mt-1 text-xs leading-5 text-slate-500">DWG-Bestand vorhanden. Für den ersten Browser-Piloten ergänzen wir PDF-Planstände; DWG-Unterstützung folgt modular.</p></div></aside>
      </div>
      <div className="mt-5 rounded-xl border border-cyan-100 bg-cyan-50/60 p-5"><h3 className="font-semibold text-cyan-900">Geplanter End-to-End-Test</h3><p className="mt-2 text-sm text-slate-700">IFC ARCH + HEI + LUE + SAN + KOORD → Gewerke überlagern → Clash auswählen → Issue erzeugen → 2D/3D Viewpoint → Revit 2027 „Show Issue“.</p></div>
    </section>
  </main>;
}
